title:              Sangeet Narayan
email:              sangeetnarayands@gmail.com
description:        Hello World!
author:             Sangeet Narayan
baseurl:            ""
url:                "https://sangeetnarayands.github.io"

# Social Profiles
twitter_username:   EightPackKebAbs
github_username:    sangeetds
facebook_username:  
instagram_username:  
linkedin_username: sangeetnarayands

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
